"""Model functions for "State, Plan, and the Graph".

Generated by sandbook. Every function here is pure: JSON in, JSON out,
no I/O, no global mutation. The verifier runs these in CPython and the
browser runs them in Pyodide, through the same bootstrap.
"""


import math



# ------------------------ state-is-the-binding

def _binding_state_for_step(step):
    step = max(1, min(6, int(step)))

    if step == 1:
        state_rows = []
        cloud_rows = []
        config_addresses = ["aws_s3_bucket.logs", "aws_s3_bucket.assets"]
        plan_actions = ["create aws_s3_bucket.logs", "create aws_s3_bucket.assets"]
        note = ("No state file yet and nothing in the cloud. The plan proposes "
                "creating both buckets, one per configuration address.")
    elif step == 2:
        state_rows = [
            {"address": "aws_s3_bucket.logs", "id": "bucket-7a1", "attrs": "name=logs"},
            {"address": "aws_s3_bucket.assets", "id": "bucket-9c4", "attrs": "name=assets"},
        ]
        cloud_rows = [
            {"id": "bucket-7a1", "attrs": "name=logs"},
            {"id": "bucket-9c4", "attrs": "name=assets"},
        ]
        config_addresses = ["aws_s3_bucket.logs", "aws_s3_bucket.assets"]
        plan_actions = []
        note = ("Apply ran. Two buckets exist in the cloud, and state now holds two "
                "rows, each binding one configuration address to one specific remote id.")
    elif step == 3:
        state_rows = [
            {"address": "aws_s3_bucket.logs", "id": "bucket-7a1", "attrs": "name=logs"},
            {"address": "aws_s3_bucket.assets", "id": "bucket-9c4", "attrs": "name=assets"},
        ]
        cloud_rows = [
            {"id": "bucket-7a1", "attrs": "name=logs"},
            {"id": "bucket-9c4", "attrs": "name=assets"},
        ]
        config_addresses = ["aws_s3_bucket.logs", "aws_s3_bucket.assets"]
        plan_actions = []
        note = ("Running plan again finds no changes. Terraform looked up "
                "aws_s3_bucket.logs and aws_s3_bucket.assets in state, found their bound "
                "ids, and compared those specific objects. It never matched by name in the cloud.")
    elif step == 4:
        state_rows = []
        cloud_rows = [
            {"id": "bucket-7a1", "attrs": "name=logs"},
            {"id": "bucket-9c4", "attrs": "name=assets"},
        ]
        config_addresses = ["aws_s3_bucket.logs", "aws_s3_bucket.assets"]
        plan_actions = ["create aws_s3_bucket.logs", "create aws_s3_bucket.assets"]
        note = ("The state file was lost. The cloud pane is unchanged, both buckets "
                "still exist, but the binding that said which address owns which id is gone. "
                "With no state row for either address, the plan proposes two creates, exactly "
                "as it did at step 1, even though the objects are sitting right there.")
    elif step == 5:
        state_rows = [
            {"address": "aws_s3_bucket.logs", "id": "bucket-3f2", "attrs": "name=logs"},
            {"address": "aws_s3_bucket.assets", "id": "bucket-5b8", "attrs": "name=assets"},
        ]
        cloud_rows = [
            {"id": "bucket-7a1", "attrs": "name=logs"},
            {"id": "bucket-9c4", "attrs": "name=assets"},
            {"id": "bucket-3f2", "attrs": "name=logs"},
            {"id": "bucket-5b8", "attrs": "name=assets"},
        ]
        config_addresses = ["aws_s3_bucket.logs", "aws_s3_bucket.assets"]
        plan_actions = []
        note = ("That plan was applied. The cloud now holds four objects: two orphans, "
                "bucket-7a1 and bucket-9c4, that no address points to any more, and two "
                "newly created ones bound to the two addresses. No error was raised, because "
                "nothing in this model checks for duplicates by name.")
    else:
        state_rows = [
            {"address": "aws_s3_bucket.logs", "id": "bucket-3f2", "attrs": "name=logs"},
            {"address": "aws_s3_bucket.assets", "id": "bucket-5b8", "attrs": "name=assets"},
        ]
        cloud_rows = [
            {"id": "bucket-7a1", "attrs": "name=logs"},
            {"id": "bucket-9c4", "attrs": "name=assets"},
            {"id": "bucket-3f2", "attrs": "name=logs"},
            {"id": "bucket-5b8", "attrs": "name=assets"},
        ]
        config_addresses = ["aws_s3_bucket.logs", "aws_s3_bucket.static"]
        plan_actions = ["create aws_s3_bucket.static", "destroy aws_s3_bucket.assets"]
        note = ("The block was renamed from aws_s3_bucket.assets to aws_s3_bucket.static. "
                "State still has a row keyed aws_s3_bucket.assets, but no config address "
                "matches that key any more. Config now asks for aws_s3_bucket.static, but no "
                "state row matches that address. The default reading is one create and one "
                "destroy of bucket-5b8, a perfectly healthy object that nothing about the "
                "real world changed.")

    return {
        "step": step,
        "state_rows": state_rows,
        "cloud_rows": cloud_rows,
        "config_addresses": config_addresses,
        "plan_actions": plan_actions,
        "note": note,
        "done": step >= 6,
    }


def state_is_binding_init():
    return _binding_state_for_step(1)


def state_is_binding_step(state):
    current_step = state.get("step", 1) if isinstance(state, dict) else 1
    return _binding_state_for_step(current_step + 1)


def state_is_binding_view(state):
    state_rows = state.get("state_rows", []) if isinstance(state, dict) else []
    cloud_rows = state.get("cloud_rows", []) if isinstance(state, dict) else []
    config_addresses = state.get("config_addresses", []) if isinstance(state, dict) else []
    plan_actions = state.get("plan_actions", []) if isinstance(state, dict) else []
    note = state.get("note", "") if isinstance(state, dict) else ""
    step = state.get("step", 1) if isinstance(state, dict) else 1

    if state_rows:
        state_row_labels = [r["address"] for r in state_rows]
        state_cells = [[r["id"], r["attrs"]] for r in state_rows]
    else:
        state_row_labels = ["(no entries)"]
        state_cells = [["", ""]]

    if cloud_rows:
        cloud_row_labels = [r["id"] for r in cloud_rows]
        cloud_cells = [[r["attrs"]] for r in cloud_rows]
    else:
        cloud_row_labels = ["(empty)"]
        cloud_cells = [[""]]

    plan_text = "Plan: " + ("; ".join(plan_actions) if plan_actions else "no changes") + "."
    config_text = "Config declares: " + ", ".join(config_addresses) + "."
    text = config_text + " " + plan_text + " " + note

    return {
        "kind": "stack",
        "caption": "Step " + str(step) + " of 6: a simplified model of state as the binding between address and remote object.",
        "panels": [
            {
                "kind": "grid",
                "caption": "State (simplified): configuration address bound to a remote id and recorded attributes.",
                "row_labels": state_row_labels,
                "col_labels": ["id", "attrs"],
                "cells": state_cells,
            },
            {
                "kind": "grid",
                "caption": "Cloud (simplified): actual objects that exist right now, independent of any address.",
                "row_labels": cloud_row_labels,
                "col_labels": ["attrs"],
                "cells": cloud_cells,
            },
            {
                "kind": "text",
                "text": text,
            },
        ],
    }


# ------------------------ three-way-plan

def plan_action(config, state, real, force_new=False):
    if config is None and state is None:
        return "no change"
    if config is not None and state is None:
        return "create"
    if config is None and state is not None:
        return "destroy"
    if real is None:
        return "create"
    if config == state == real:
        return "no change"
    if config == real and state != real:
        return "no change"
    if config != real:
        return "replace" if force_new else "update in place"
    return "no change"


def plan_action(config, state, real, force_new=False):
    if config is None and state is None:
        return "no change"
    if config is not None and state is None:
        return "create"
    if config is None and state is not None:
        return "destroy"
    if real is None:
        return "create"
    if config == state == real:
        return "no change"
    if config == real and state != real:
        return "no change"
    if config != real:
        return "replace" if force_new else "update in place"
    return "no change"


def three_way_grid_view():
    scenarios = [
        {"desc": "1. All three agree (tags unchanged)",
         "config": {"tags": {"env": "prod"}}, "state": {"tags": {"env": "prod"}},
         "real": {"tags": {"env": "prod"}}, "force_new": False},
        {"desc": "2. Ordinary code change not yet applied",
         "config": {"instance_type": "m5.large"}, "state": {"instance_type": "t3.micro"},
         "real": {"instance_type": "t3.micro"}, "force_new": False},
        {"desc": "3. Someone hand-edited the object in the console",
         "config": {"instance_type": "t3.micro"}, "state": {"instance_type": "t3.micro"},
         "real": {"instance_type": "m5.large"}, "force_new": False},
        {"desc": "4. Record is stale but object already matches config",
         "config": {"instance_type": "m5.large"}, "state": {"instance_type": "t3.micro"},
         "real": {"instance_type": "m5.large"}, "force_new": False},
        {"desc": "5. Object deleted outside Terraform, config still wants it",
         "config": {"instance_type": "t3.micro"}, "state": {"instance_type": "t3.micro"},
         "real": None, "force_new": False},
        {"desc": "6. Brand new resource block, nothing exists yet",
         "config": {"instance_type": "t3.micro"}, "state": None, "real": None, "force_new": False},
        {"desc": "7. Resource block deleted from config, state entry and object remain",
         "config": None, "state": {"instance_type": "t3.micro"},
         "real": {"instance_type": "t3.micro"}, "force_new": False},
        {"desc": "8. Config changes a force-new field (availability_zone)",
         "config": {"availability_zone": "us-east-1b"}, "state": {"availability_zone": "us-east-1a"},
         "real": {"availability_zone": "us-east-1a"}, "force_new": True},
    ]

    def fmt(card):
        if card is None:
            return "(none)"
        parts = []
        for k in sorted(card.keys()):
            parts.append(str(k) + "=" + str(card[k]))
        return ", ".join(parts)

    rows = []
    row_labels = []
    for s in scenarios:
        action = plan_action(s["config"], s["state"], s["real"], s["force_new"])
        rows.append([fmt(s["config"]), fmt(s["state"]), fmt(s["real"]), action])
        row_labels.append(s["desc"])

    return {
        "kind": "grid",
        "row_labels": row_labels,
        "column_labels": ["Config", "State", "Real object", "Proposed action"],
        "cells": rows,
        "caption": "Each row is one scenario built from the same three cards: config, state, real. The proposed action depends on which pair disagrees, config vs state, state vs real, or config vs real, and, when config and the real object disagree, on whether the changed attribute forces replacement: compare rows 2 and 8, same disagreement pattern, different actions. Nothing depends on file order, block order, or which value looks newest. Row 7 proposes a destroy; dropping a resource from tracking while keeping the object requires an explicit state removal."
    }


# ------------------------ edges-from-references

def grade_edges(submission):
    import re

    text = submission if isinstance(submission, str) else str(submission)

    def parse(cfg_text):
        pattern = re.compile(r'resource\s+"([\w]+)"\s+"([\w]+)"\s*\{(.*?)\n\}', re.DOTALL)
        out = []
        for m in pattern.finditer(cfg_text):
            out.append({"type": m.group(1), "name": m.group(2), "body": m.group(3)})
        return out

    def addr_of(r):
        return f"{r['type']}.{r['name']}"

    try:
        resources = parse(text)
    except Exception:
        return {
            "passed": False,
            "message": "Could not parse the config.",
            "details": [{"label": "parse", "ok": False,
                          "note": "The config text could not be parsed into resource blocks. Check that every block is closed with a line containing only '}'."}],
            "view": None,
        }

    if not resources:
        return {
            "passed": False,
            "message": "No resource blocks were found.",
            "details": [{"label": "parse", "ok": False,
                          "note": "No 'resource \"type\" \"name\" { ... }' blocks were found. Each block's closing brace must sit on its own line."}],
            "view": None,
        }

    addrs = {addr_of(r) for r in resources}
    edges = []
    ref_pairs = set()
    redundant = []

    for r in resources:
        addr = addr_of(r)
        seen = set()
        for rt, rn, ra in re.findall(r'\$\{([\w]+)\.([\w]+)\.([\w]+)\}', r["body"]):
            target = f"{rt}.{rn}"
            if target == addr or target in seen:
                continue
            seen.add(target)
            edges.append((addr, target, "reference"))
            ref_pairs.add((addr, target))

        dep_match = re.search(r'depends_on\s*=\s*\[(.*?)\]', r["body"], re.DOTALL)
        if dep_match:
            for item in re.findall(r'"([\w\.]+)"', dep_match.group(1)):
                if item == addr:
                    continue
                if (addr, item) in ref_pairs:
                    redundant.append((addr, item))
                else:
                    edges.append((addr, item, "depends_on"))

    if redundant:
        frm, to = redundant[0]
        return {
            "passed": False,
            "message": f"{frm} has depends_on = [\"{to}\"] but an expression already reads {to}'s attributes, so that edge exists already.",
            "details": [{
                "label": "redundant depends_on",
                "ok": False,
                "note": f"{frm} already depends on {to} because of an ${{...}} reference in its body. The extra depends_on is inert; remove it.",
            }],
            "view": None,
        }

    graph = {}
    for frm, to, _ in edges:
        graph.setdefault(frm, set()).add(to)
    for a in addrs:
        graph.setdefault(a, set())

    def find_cycle():
        visited = set()
        onstack = []
        onstack_set = set()

        def dfs(node):
            visited.add(node)
            onstack.append(node)
            onstack_set.add(node)
            for nxt in sorted(graph.get(node, [])):
                if nxt in onstack_set:
                    i = onstack.index(nxt)
                    return onstack[i:] + [nxt]
                if nxt not in visited:
                    found = dfs(nxt)
                    if found:
                        return found
            onstack.pop()
            onstack_set.discard(node)
            return None

        for a in sorted(graph.keys()):
            if a not in visited:
                found = dfs(a)
                if found:
                    return found
        return None

    cycle = find_cycle()
    if cycle:
        return {
            "passed": False,
            "message": "The dependency graph has a cycle: " + " -> ".join(cycle),
            "details": [{
                "label": "acyclic",
                "ok": False,
                "note": "A resource graph must be a DAG. Remove one of the references in this cycle: " + " -> ".join(cycle),
            }],
            "view": None,
        }

    pairs = {(f, t) for f, t, _ in edges}
    expected = {
        ("aws_subnet.main", "aws_vpc.main"),
        ("aws_security_group.sg", "aws_vpc.main"),
        ("aws_instance.app", "aws_subnet.main"),
        ("aws_instance.app", "aws_iam_role_policy.policy"),
    }

    vpc_ok = ("aws_subnet.main", "aws_vpc.main") in pairs and ("aws_security_group.sg", "aws_vpc.main") in pairs
    instance_ref_ok = ("aws_instance.app", "aws_subnet.main", "reference") in edges
    policy_dep_ok = ("aws_instance.app", "aws_iam_role_policy.policy", "depends_on") in edges
    exact_ok = pairs == expected

    details = [
        {"label": "subnet and security group reference the vpc", "ok": vpc_ok,
         "note": "aws_subnet.main and aws_security_group.sg must both read ${aws_vpc.main.id} somewhere in their body."},
        {"label": "instance depends on subnet via a reference, not a literal", "ok": instance_ref_ok,
         "note": "aws_instance.app still hardcodes subnet_id as a literal string. Replace it with ${aws_subnet.main.id} so the edge comes from an expression."},
        {"label": "instance depends on the IAM role policy via depends_on", "ok": policy_dep_ok,
         "note": "Add an aws_iam_role_policy resource and put depends_on = [\"aws_iam_role_policy.policy\"] on aws_instance.app. No expression reads the policy's attributes, so only depends_on can create this edge."},
        {"label": "edge set matches exactly, nothing extra or missing", "ok": exact_ok,
         "note": f"Found edges {sorted(pairs)}, expected {sorted(expected)}."},
    ]

    passed = all(d["ok"] for d in details)
    message = "All four edges are present and nothing extra was added." if passed else "The edge set does not match yet."

    view = {
        "kind": "text",
        "text": "Adjacency list:\n" + "\n".join(
            f"{a} -> {', '.join(sorted(graph[a])) if graph[a] else '(no dependencies)'}"
            for a in sorted(graph.keys())
        ),
        "caption": "Each line reads 'this resource depends on these'. Every edge came from a ${...} reference or a depends_on list, never from the order the blocks appear in the file.",
    }

    return {"passed": passed, "message": message, "details": details, "view": view}


# ------------------------ walk-not-write-order

def dag_schedule(concurrency, duration_profile):
    nodes = ["vpc", "s3_bucket", "subnet_a", "subnet_b", "security_group",
             "instance_1", "instance_2", "instance_3"]
    deps = {
        "vpc": [],
        "s3_bucket": [],
        "subnet_a": ["vpc"],
        "subnet_b": ["vpc"],
        "security_group": ["vpc"],
        "instance_1": ["subnet_a", "security_group"],
        "instance_2": ["subnet_a"],
        "instance_3": ["subnet_b", "security_group"],
    }
    if duration_profile == "vpc_slow":
        durations = {"vpc": 20, "s3_bucket": 3, "subnet_a": 3, "subnet_b": 3,
                     "security_group": 3, "instance_1": 3, "instance_2": 3, "instance_3": 3}
    elif duration_profile == "instances_slow":
        durations = {"vpc": 3, "s3_bucket": 3, "subnet_a": 3, "subnet_b": 3,
                     "security_group": 3, "instance_1": 15, "instance_2": 15, "instance_3": 15}
    else:
        durations = {n: 3 for n in nodes}

    concurrency = max(1, int(concurrency))

    remaining = set(nodes)
    finish_times = {}
    start_times = {}
    running = {}
    time = 0.0
    guard = 0

    while (remaining or running) and guard < 1000:
        guard += 1
        ready = [n for n in nodes if n in remaining and all(d in finish_times for d in deps[n])]
        while ready and len(running) < concurrency:
            n = ready.pop(0)
            start_times[n] = time
            running[n] = time + durations[n]
            remaining.discard(n)
        if not running:
            break
        next_time = min(running.values())
        time = next_time
        done_now = [n for n, t in running.items() if t <= time]
        for n in done_now:
            finish_times[n] = running[n]
            del running[n]

    total_time = max(finish_times.values()) if finish_times else 0.0

    schedule = []
    for n in nodes:
        schedule.append({
            "node": n,
            "start": start_times.get(n, 0.0),
            "end": finish_times.get(n, start_times.get(n, 0.0)),
        })

    return {
        "nodes": nodes,
        "schedule": schedule,
        "total_time": total_time,
        "concurrency": concurrency,
        "duration_profile": duration_profile,
    }


def total_apply_time(concurrency, duration_profile):
    result = dag_schedule(concurrency, duration_profile)
    return float(result["total_time"])


def critical_path_time(duration_profile):
    nodes = ["vpc", "s3_bucket", "subnet_a", "subnet_b", "security_group",
             "instance_1", "instance_2", "instance_3"]
    deps = {
        "vpc": [],
        "s3_bucket": [],
        "subnet_a": ["vpc"],
        "subnet_b": ["vpc"],
        "security_group": ["vpc"],
        "instance_1": ["subnet_a", "security_group"],
        "instance_2": ["subnet_a"],
        "instance_3": ["subnet_b", "security_group"],
    }
    if duration_profile == "vpc_slow":
        durations = {"vpc": 20, "s3_bucket": 3, "subnet_a": 3, "subnet_b": 3,
                     "security_group": 3, "instance_1": 3, "instance_2": 3, "instance_3": 3}
    elif duration_profile == "instances_slow":
        durations = {"vpc": 3, "s3_bucket": 3, "subnet_a": 3, "subnet_b": 3,
                     "security_group": 3, "instance_1": 15, "instance_2": 15, "instance_3": 15}
    else:
        durations = {n: 3 for n in nodes}

    finish = {}
    for n in nodes:
        start = max([finish[d] for d in deps[n]], default=0.0)
        finish[n] = start + durations[n]
    return float(max(finish.values()))


def apply_timeline_view(concurrency, duration_profile, shuffle_seed):
    result = dag_schedule(concurrency, duration_profile)
    schedule = result["schedule"]
    total_time = result["total_time"]
    nodes = result["nodes"]
    conc = result["concurrency"]

    bucket_size = 1
    if total_time > 30:
        bucket_size = int(total_time // 30) + 1
    bucket_count = max(1, int(total_time // bucket_size) + 1)
    column_labels = [str(i * bucket_size) for i in range(bucket_count)]

    cells = []
    for row in schedule:
        start = row["start"]
        end = row["end"]
        node_row = []
        for i in range(bucket_count):
            bucket_start = i * bucket_size
            bucket_end = bucket_start + bucket_size
            running = 1 if (start < bucket_end and end > bucket_start) else 0
            node_row.append(running)
        cells.append(node_row)

    grid_panel = {
        "kind": "grid",
        "row_labels": nodes,
        "column_labels": column_labels,
        "cells": cells,
        "x_label": "seconds since apply started",
        "y_label": "resource",
        "caption": "Each row is a resource; a filled cell means it is applying during that second. Rows fill in whatever order the graph allows, never in the order the file lists them.",
    }

    shuffle_orders = {
        0: ["vpc", "subnet_a", "subnet_b", "security_group", "instance_1", "instance_2", "instance_3", "s3_bucket"],
        1: ["s3_bucket", "instance_2", "vpc", "instance_1", "subnet_b", "security_group", "subnet_a", "instance_3"],
        2: ["instance_3", "subnet_a", "s3_bucket", "security_group", "vpc", "instance_1", "subnet_b", "instance_2"],
        3: ["security_group", "instance_1", "subnet_b", "s3_bucket", "instance_3", "vpc", "instance_2", "subnet_a"],
        4: ["instance_1", "security_group", "instance_3", "subnet_a", "instance_2", "vpc", "s3_bucket", "subnet_b"],
    }
    seed_key = int(shuffle_seed)
    if seed_key not in shuffle_orders:
        seed_key = 0
    file_order = shuffle_orders[seed_key]
    listing_lines = ["{}. resource \"{}\"".format(i + 1, n) for i, n in enumerate(file_order)]
    listing_text = "File listing (this order is cosmetic only):\n" + "\n".join(listing_lines)

    text_panel = {
        "kind": "text",
        "text": listing_text,
        "caption": "Shuffle this list and watch the timeline above: it does not move, because the file's order carries no ordering information at all.",
    }

    scalars_panel = {
        "kind": "scalars",
        "items": [
            {"label": "Total apply time", "value": float(total_time), "unit": "s"},
            {"label": "Concurrency (model setting)", "value": float(conc), "unit": ""},
        ],
        "value_format": ".1f",
    }

    if conc >= 2:
        order_note = ("At this concurrency, s3_bucket starts immediately alongside vpc: nothing in the graph "
                       "connects them, so both begin at time zero regardless of where s3_bucket sits in the file listing.")
    else:
        order_note = ("At concurrency 1 only one resource runs at a time. The row order above is one valid serial "
                       "order; several different orderings would satisfy this same graph equally well.")

    if conc >= 3:
        width_note = (" Total time has already flattened to the critical path length: the widest level of this "
                       "graph has three nodes, so raising concurrency past 3 finishes the apply no sooner.")
    else:
        width_note = ""

    return {
        "kind": "stack",
        "panels": [grid_panel, text_panel, scalars_panel],
        "caption": order_note + width_note,
    }


# ------------------------ backwards-for-destroy

def bwd_graph_nodes():
    return ["vpc", "subnet", "security_group", "route_table",
            "instance_1", "instance_2", "instance_3", "eip", "load_balancer"]


def bwd_graph_edges():
    return [
        ["vpc", "subnet"],
        ["vpc", "security_group"],
        ["vpc", "route_table"],
        ["subnet", "instance_1"],
        ["security_group", "instance_1"],
        ["subnet", "instance_2"],
        ["security_group", "instance_2"],
        ["subnet", "instance_3"],
        ["security_group", "instance_3"],
        ["instance_1", "eip"],
        ["subnet", "load_balancer"],
        ["instance_1", "load_balancer"],
        ["instance_2", "load_balancer"],
        ["instance_3", "load_balancer"],
    ]


def bwd_topo_create_order():
    nodes = bwd_graph_nodes()
    edges = bwd_graph_edges()
    indeg = {n: 0 for n in nodes}
    adj = {n: [] for n in nodes}
    for a, b in edges:
        adj[a].append(b)
        indeg[b] = indeg.get(b, 0) + 1
    ready = sorted([n for n in nodes if indeg[n] == 0])
    order = []
    while ready:
        ready.sort()
        n = ready.pop(0)
        order.append(n)
        for m in adj[n]:
            indeg[m] -= 1
            if indeg[m] == 0:
                ready.append(m)
    return order


def bwd_downstream(node):
    edges = bwd_graph_edges()
    adj = {}
    for a, b in edges:
        adj.setdefault(a, []).append(b)
    seen = set()
    result = []
    stack = [node]
    while stack:
        cur = stack.pop()
        for nxt in sorted(adj.get(cur, [])):
            if nxt not in seen:
                seen.add(nxt)
                result.append(nxt)
                stack.append(nxt)
    return result


def bwd_mode_queue(mode):
    create_order = bwd_topo_create_order()
    destroy_order = list(reversed(create_order))
    if mode == "full_destroy":
        return destroy_order
    if mode == "replace_instance3":
        target = "instance_3"
    else:
        target = "vpc"
    downstream = set(bwd_downstream(target))
    queue = [n for n in destroy_order if n in downstream]
    queue.append(target)
    return queue


def backwards_destroy_init(mode):
    queue = bwd_mode_queue(mode)
    return {
        "mode": mode,
        "queue": queue,
        "total": len(queue),
        "step_num": 0,
        "affected": [],
        "done": len(queue) == 0,
    }


def backwards_destroy_step(state):
    if state.get("done"):
        return dict(state)
    queue = state["queue"]
    idx = state["step_num"]
    node = queue[idx]
    new_affected = state["affected"] + [node]
    new_step = idx + 1
    new_done = new_step >= len(queue)
    return {
        "mode": state["mode"],
        "queue": queue,
        "total": state["total"],
        "step_num": new_step,
        "affected": new_affected,
        "done": new_done,
    }


def backwards_destroy_view(state):
    destroy_order = list(reversed(bwd_topo_create_order()))
    affected = state.get("affected", [])
    mode = state.get("mode", "replace_vpc")
    total = state.get("total", len(destroy_order))
    labels = destroy_order
    values = [1 if n in affected else 0 for n in destroy_order]
    if mode == "full_destroy":
        caption = (
            "Full destroy walks the nine-node graph in reverse. Leaves like load_balancer go "
            "first, the three instances and eip clear before subnet and security_group, and vpc, "
            "the node everything else traces back to, goes last. "
            + str(len(affected)) + " of 9 resources destroyed so far."
        )
    elif mode == "replace_instance3":
        caption = (
            "instance_3 is marked force-new. Its downstream reachable set is one resource, "
            "load_balancer, so only two resources move in total. "
            + str(len(affected)) + " of " + str(total) + " affected resources handled so far."
        )
    else:
        caption = (
            "vpc is marked force-new. Nothing downstream can keep existing once vpc is gone, so "
            "all eight resources that trace back to vpc are destroyed first, in the same order a "
            "full destroy would use, and then vpc itself goes before everything rebuilds. "
            + str(len(affected)) + " of " + str(total) + " affected resources handled so far."
        )
    return {
        "kind": "stack",
        "panels": [
            {
                "kind": "bars",
                "labels": labels,
                "values": values,
                "x_label": "resource, in destroy order",
                "y_label": "handled",
                "y_min": 0,
                "y_max": 1,
                "value_format": "d",
                "caption": caption,
            },
            {
                "kind": "scalars",
                "items": [
                    {"label": "step", "value": state.get("step_num", 0)},
                    {"label": "affected so far", "value": len(affected)},
                    {"label": "total to handle", "value": total},
                ],
            },
        ],
    }
