"""Model functions for "Replay-Safe Temporal Workflows".

Generated by sandbook. Every function here is pure: JSON in, JSON out,
no I/O, no global mutation. The verifier runs these in CPython and the
browser runs them in Pyodide, through the same bootstrap.
"""


import math



# ------------------------ what-replay-actually-does

def replay_script_data():
    e1 = "WorkflowExecutionStarted"
    e2 = "ActivityTaskScheduled(charge_card)"
    e3 = "ActivityTaskCompleted(charge_card) -> txn_881"
    e4 = "TimerStarted(1h)"
    e5 = "TimerFired"
    e6 = "ActivityTaskScheduled(send_receipt)"
    e7 = "ActivityTaskCompleted(send_receipt) -> ok"
    e8 = "WorkflowExecutionCompleted"
    return [
        {
            "history": [e1, e2],
            "line": "charge = await charge_card(order)",
            "commands_emitted": ["ActivityTaskScheduled(charge_card)"],
            "is_replaying": False,
            "worker": "W1",
            "note": "Task 1: fresh execution, nothing recorded yet to replay against. The worker runs the code live and emits ActivityTaskScheduled for charge_card as a brand new command.",
        },
        {
            "history": [e1, e2, e3],
            "line": "charge = await charge_card(order)",
            "commands_emitted": [],
            "is_replaying": True,
            "worker": "W1",
            "note": "Task 2 starts because charge_card finished. The worker replays from the top: it reaches the charge_card call, finds ActivityTaskScheduled already in history, emits no new command, and reads txn_881 straight out of the recorded ActivityTaskCompleted event instead of calling the activity again.",
        },
        {
            "history": [e1, e2, e3, e4],
            "line": "await workflow.sleep(timedelta(hours=1))",
            "commands_emitted": ["TimerStarted(1h)"],
            "is_replaying": False,
            "worker": "W1",
            "note": "Replay runs out of recorded events right here. There is nothing left to match, so the worker flips to live and emits a genuinely new command: TimerStarted for one hour.",
        },
        {
            "history": [e1, e2, e3, e4, e5],
            "line": "await workflow.sleep(timedelta(hours=1))",
            "commands_emitted": [],
            "is_replaying": False,
            "worker": "W1",
            "note": "An hour passes, the timer fires, and TimerFired is appended to history on the server. Worker W1 crashes immediately after this, before it can start the next task. The history is unaffected: it lives on the server, not on the worker.",
        },
        {
            "history": [e1, e2, e3, e4, e5],
            "line": "charge = await charge_card(order)",
            "commands_emitted": [],
            "is_replaying": True,
            "worker": "W2",
            "note": "A fresh worker, W2, picks up the workflow task. It has no memory of anything, so it replays from line one. It reaches charge_card, matches ActivityTaskScheduled in history, and hands back txn_881 from the recorded completion. charge_card is NOT called a second time: no request goes out, no card is charged again.",
        },
        {
            "history": [e1, e2, e3, e4, e5],
            "line": "await workflow.sleep(timedelta(hours=1))",
            "commands_emitted": [],
            "is_replaying": True,
            "worker": "W2",
            "note": "W2 keeps replaying: TimerStarted and TimerFired are both already sitting in history, so the sleep resolves instantly during replay. No new commands, no real waiting.",
        },
        {
            "history": [e1, e2, e3, e4, e5, e6],
            "line": "await send_receipt(charge)",
            "commands_emitted": ["ActivityTaskScheduled(send_receipt)"],
            "is_replaying": False,
            "worker": "W2",
            "note": "Replay runs out of history exactly here. is_replaying flips from True to False and W2 goes live, emitting a real new command: ActivityTaskScheduled for send_receipt.",
        },
        {
            "history": [e1, e2, e3, e4, e5, e6, e7],
            "line": "await send_receipt(charge)",
            "commands_emitted": [],
            "is_replaying": True,
            "worker": "W2",
            "note": "send_receipt completes and a new task starts. W2 (still warm this time, no crash) replays up to the send_receipt call, matches it in history, and reads back the recorded result 'ok' instead of sending the receipt again.",
        },
        {
            "history": [e1, e2, e3, e4, e5, e6, e7, e8],
            "line": "return",
            "commands_emitted": ["WorkflowExecutionCompleted"],
            "is_replaying": False,
            "worker": "W2",
            "note": "Replay catches up one last time, flips live, and the final line emits WorkflowExecutionCompleted. The workflow is done. charge_card ran once and send_receipt ran once, total, across both workers and every replay.",
        },
    ]


def replay_sim_init():
    return {
        "step": 0,
        "history": ["WorkflowExecutionStarted"],
        "line": "(workflow function entered)",
        "commands_emitted": [],
        "is_replaying": False,
        "worker": "W1",
        "note": "Task 1 begins. History holds one event so far, WorkflowExecutionStarted. The worker is about to run the workflow code live for the first time ever.",
        "done": False,
    }


def replay_sim_step(state):
    script = replay_script_data()
    idx = state.get("step", 0)
    if idx >= len(script):
        new_state = dict(state)
        new_state["done"] = True
        return new_state
    entry = script[idx]
    new_step = idx + 1
    new_state = dict(entry)
    new_state["step"] = new_step
    new_state["done"] = new_step >= len(script)
    return new_state


def replay_sim_view(state):
    history = state.get("history", [])
    line = state.get("line", "")
    worker = state.get("worker", "")
    is_replaying = state.get("is_replaying", False)
    commands = state.get("commands_emitted", [])
    note = state.get("note", "")
    row_labels = [str(i + 1) for i in range(len(history))]
    cells = [[event] for event in history]
    commands_text = ", ".join(commands) if commands else "none (matched an existing history event)"
    state_text = (
        "Worker " + str(worker) + " is at `" + str(line) + "`. is_replaying = " +
        str(is_replaying) + ". Commands emitted this task: " + commands_text + "."
    )
    return {
        "kind": "stack",
        "caption": note,
        "panels": [
            {
                "kind": "grid",
                "row_labels": row_labels,
                "col_labels": ["Event"],
                "cells": cells,
                "caption": "The event history recorded on the Temporal server. Every worker, old or new, replays workflow code against exactly this list.",
            },
            {
                "kind": "text",
                "text": state_text,
                "caption": note,
            },
        ],
    }


# ------------------------ which-line-breaks-replay

def classify_unsafe_lines():
    # Order matches the six snippets shown in the question:
    # 1 random.randint, 2 workflow.random, 3 datetime.now, 4 workflow.now,
    # 5 dict iteration, 6 requests.get
    return [True, False, True, False, False, True]


def workflow_lines_view():
    lines = [
        "random.randint(1, 100)",
        "workflow.random().randint(1, 100)",
        "datetime.now()",
        "workflow.now()",
        "for k in some_dict: await act(k)",
        "requests.get(url)",
    ]
    verdicts = ["UNSAFE", "SAFE", "UNSAFE", "SAFE", "SAFE", "UNSAFE"]
    reasons = [
        "Stdlib random reseeds on every process start; replay draws a different value. Use workflow.random().",
        "workflow.random() records its draw as a marker event, so replay reads the same value back.",
        "Wall-clock time differs between the original run and any later replay. Use workflow.now().",
        "workflow.now() reads the time recorded in workflow history, so replay sees the same value.",
        "Python 3.7+ dicts preserve insertion order, and the dict was built earlier in the same deterministic run, so iteration order is identical on replay.",
        "The HTTP response is never written to history, and the call blocks the workflow task. Move it into an activity.",
    ]
    cells = [[lines[i], verdicts[i], reasons[i]] for i in range(6)]
    return {
        "kind": "grid",
        "row_labels": [f"Line {i + 1}" for i in range(6)],
        "col_labels": ["Code", "Verdict", "Why"],
        "cells": cells,
        "caption": "Three lines are non-deterministic because their result is never recorded in workflow history (1, 3, 6). The other three are safe: two because they use the SDK's replay-aware equivalents (2, 4), and one because Python's dict-ordering guarantee makes plain iteration deterministic all by itself (5).",
    }


# ------------------------ reading-a-retry-schedule

def resolve_retry_config(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts):
    presets = {
        "sdk_default": {"initial_interval": 1.0, "backoff_coefficient": 2.0, "maximum_interval": 100.0, "maximum_attempts": 0},
        "fast_idempotent": {"initial_interval": 0.1, "backoff_coefficient": 2.0, "maximum_interval": 5.0, "maximum_attempts": 10},
        "slow_external": {"initial_interval": 5.0, "backoff_coefficient": 2.0, "maximum_interval": 300.0, "maximum_attempts": 8},
        "linear": {"initial_interval": 10.0, "backoff_coefficient": 1.0, "maximum_interval": 100.0, "maximum_attempts": 5},
    }
    if preset in presets:
        p = presets[preset]
        return {
            "initial_interval": p["initial_interval"],
            "backoff_coefficient": p["backoff_coefficient"],
            "maximum_interval": p["maximum_interval"],
            "maximum_attempts": p["maximum_attempts"],
        }
    return {
        "initial_interval": initial_interval,
        "backoff_coefficient": backoff_coefficient,
        "maximum_interval": maximum_interval,
        "maximum_attempts": maximum_attempts,
    }


def retry_schedule(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration):
    cfg = resolve_retry_config(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts)
    ii = cfg["initial_interval"]
    bc = cfg["backoff_coefficient"]
    mi = cfg["maximum_interval"]
    ma = cfg["maximum_attempts"]
    n_attempts = ma if ma and ma > 0 else 20
    n_attempts = int(min(n_attempts, 20))
    if n_attempts < 1:
        n_attempts = 1
    attempt_numbers = []
    starts = []
    intervals = []
    cumulative = []
    capped_at = None
    start = 0.0
    for n in range(1, n_attempts + 1):
        if n == 1:
            interval = 0.0
        else:
            raw = ii * (bc ** (n - 2))
            interval = raw if raw < mi else mi
            if capped_at is None and raw >= mi:
                capped_at = n
            start = start + attempt_duration + interval
        attempt_numbers.append(n)
        starts.append(round(start, 3))
        intervals.append(round(interval, 3))
        cumulative.append(round(start + attempt_duration, 3))
    total_elapsed = starts[-1] if starts else 0.0
    return {
        "attempt_numbers": attempt_numbers,
        "starts": starts,
        "intervals": intervals,
        "cumulative": cumulative,
        "total_elapsed": round(total_elapsed, 3),
        "n_attempts": n_attempts,
        "capped_at": capped_at if capped_at is not None else n_attempts,
    }


def retry_table_view(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration):
    sched = retry_schedule(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration)
    row_labels = [str(n) for n in sched["attempt_numbers"]]
    col_labels = ["Start (s)", "Interval before (s)", "Elapsed after (s)"]
    cells = []
    for i in range(len(row_labels)):
        cells.append([sched["starts"][i], sched["intervals"][i], sched["cumulative"][i]])
    caption = (
        "Each row is one attempt. Start is the wall-clock time the attempt begins; interval before is the "
        "backoff wait after the previous attempt failed, not before it starts. Attempt " + str(sched["n_attempts"]) +
        " begins at " + str(sched["total_elapsed"]) + "s, which is attempt duration plus every prior interval, "
        "not just the sum of intervals."
    )
    return {
        "kind": "grid",
        "row_labels": row_labels,
        "col_labels": col_labels,
        "cells": cells,
        "caption": caption,
    }


def retry_bars_view(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration):
    sched = retry_schedule(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration)
    labels = [str(n) for n in sched["attempt_numbers"]]
    values = sched["intervals"]
    highlight = [i for i, n in enumerate(sched["attempt_numbers"]) if n >= sched["capped_at"]]
    caption = (
        "Interval before each attempt. Growth is exponential until it hits maximumInterval, then it flattens: "
        "from attempt " + str(sched["capped_at"]) + " onward every wait is clamped to the ceiling, however many "
        "attempts remain."
    )
    return {
        "kind": "bars",
        "labels": labels,
        "values": values,
        "x_label": "Attempt",
        "y_label": "Interval before attempt (s)",
        "highlight": highlight,
        "caption": caption,
    }


def retry_stack_view(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration):
    table = retry_table_view(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration)
    bars = retry_bars_view(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration)
    return {"kind": "stack", "panels": [bars, table]}


def total_elapsed_readout(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration):
    sched = retry_schedule(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration)
    return sched["total_elapsed"]


def capped_at_attempt_readout(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration):
    sched = retry_schedule(preset, initial_interval, backoff_coefficient, maximum_interval, maximum_attempts, attempt_duration)
    return sched["capped_at"]


# ------------------------ write-a-replay-safe-workflow

def audit_command_log(commands):
    """Inspect a captured list of workflow commands for replay-safety signals.

    `commands` is a list of dicts, each shaped like one of:
      {"op": "uuid4", "value": ...}
      {"op": "now", "value": ...}
      {"op": "sleep", "seconds": ...}
      {"op": "execute_activity", "activity": ..., "arg": {...},
       "start_to_close": number or None, "maximum_attempts": int or None}

    Returns a plain dict summarizing the sequence so a caller can assert on
    it without re-walking the raw log.
    """
    op_sequence = []
    has_activity = False
    start_to_close = None
    maximum_attempts = None
    idem_key = None

    for entry in commands:
        if not isinstance(entry, dict):
            continue
        op = entry.get("op")
        op_sequence.append(op)
        if op == "execute_activity":
            has_activity = True
            start_to_close = entry.get("start_to_close")
            maximum_attempts = entry.get("maximum_attempts")
            arg = entry.get("arg")
            if isinstance(arg, dict):
                idem_key = arg.get("idem_key")

    has_bounded_retries = isinstance(maximum_attempts, int) and maximum_attempts > 0

    return {
        "op_sequence": op_sequence,
        "has_activity": has_activity,
        "start_to_close": start_to_close,
        "maximum_attempts": maximum_attempts,
        "idem_key": idem_key,
        "has_timeout": start_to_close is not None,
        "has_bounded_retries": has_bounded_retries,
    }
