"""Model functions for "KV-Caching in Transformer Inference".

Generated by sandbook. Every function here is pure: JSON in, JSON out,
no I/O, no global mutation. The verifier runs these in CPython and the
browser runs them in Pyodide, through the same bootstrap.
"""


import math



# ------------------------ recompute-vs-cache

def kvcache_constants():
    return {
        "embeddings": [
            [0.10, 0.20, -0.10, 0.05],
            [0.30, -0.10, 0.20, 0.10],
            [-0.20, 0.15, 0.05, 0.25],
            [0.05, 0.05, 0.30, -0.15],
            [0.25, -0.05, -0.10, 0.20],
            [-0.10, 0.10, 0.15, 0.05],
        ],
        "Wq": [
            [0.2, 0.1, 0.0, -0.1],
            [0.1, 0.3, -0.2, 0.0],
            [0.0, -0.1, 0.2, 0.1],
            [-0.1, 0.0, 0.1, 0.3],
        ],
        "Wk": [
            [0.15, -0.05, 0.1, 0.0],
            [0.05, 0.2, 0.0, -0.1],
            [-0.1, 0.0, 0.25, 0.05],
            [0.0, 0.1, -0.05, 0.2],
        ],
        "Wv": [
            [0.1, 0.0, 0.05, 0.15],
            [0.0, 0.2, 0.1, -0.05],
            [0.05, -0.1, 0.15, 0.0],
            [0.2, 0.05, 0.0, 0.1],
        ],
    }


def kvcache_linear(vec, W):
    return [sum(W[i][j] * vec[j] for j in range(len(vec))) for i in range(len(W))]


def kvcache_softmax(scores):
    import math
    m = max(scores)
    exps = [math.exp(s - m) for s in scores]
    total = sum(exps)
    return [e / total for e in exps]


def kvcache_attn_output(q, keys, values):
    import math
    scale = 1.0 / math.sqrt(len(q))
    scores = [sum(q[i] * k[i] for i in range(len(q))) * scale for k in keys]
    weights = kvcache_softmax(scores)
    dim = len(values[0])
    out = [0.0] * dim
    for w, v in zip(weights, values):
        for i in range(dim):
            out[i] += w * v[i]
    return out


def recompute_kv_init():
    return {
        "step": 0,
        "t": 3,
        "no_cache_total": 0,
        "cached_total": 0,
        "output_nocache": [0.0, 0.0, 0.0, 0.0],
        "output_cached": [0.0, 0.0, 0.0, 0.0],
        "done": False,
    }


def recompute_kv_step(state):
    c = kvcache_constants()
    E = c["embeddings"]
    Wq = c["Wq"]
    Wk = c["Wk"]
    Wv = c["Wv"]
    new_step = state["step"] + 1
    t = 3 + new_step
    keys = [kvcache_linear(E[i], Wk) for i in range(t)]
    values = [kvcache_linear(E[i], Wv) for i in range(t)]
    q = kvcache_linear(E[t - 1], Wq)
    out = kvcache_attn_output(q, keys, values)
    out_rounded = [round(x, 3) for x in out]
    no_cache_total = state["no_cache_total"] + t
    cached_total = state["cached_total"] + 1
    done = new_step >= 3
    return {
        "step": new_step,
        "t": t,
        "no_cache_total": no_cache_total,
        "cached_total": cached_total,
        "output_nocache": out_rounded,
        "output_cached": out_rounded,
        "done": done,
    }


def recompute_kv_view(state):
    t = state["t"]
    step = state["step"]

    def build_row(mode):
        row = []
        for p in range(1, 7):
            if step == 0:
                row.append(0.4 if p <= t else 0.0)
            else:
                if mode == "nocache":
                    row.append(1.0 if p <= t else 0.0)
                else:
                    if p == t:
                        row.append(1.0)
                    elif p < t:
                        row.append(0.4)
                    else:
                        row.append(0.0)
        return row

    grid = {
        "kind": "grid",
        "row_labels": ["no cache: recompute all K/V up to t", "cached: reuse stored K/V"],
        "col_labels": ["pos 1", "pos 2", "pos 3", "pos 4", "pos 5", "pos 6"],
        "cells": [build_row("nocache"), build_row("cached")],
        "value_format": ".1f",
        "caption": "1.0 = K/V projected fresh this step, 0.4 = already in the cache and just read, 0.0 = not reached yet. The no-cache row relights every position up to t on every single step; the cached row only ever lights one new column.",
    }

    scalars = {
        "kind": "scalars",
        "items": [
            {"label": "K/V row-projections so far \u2014 no cache", "value": state["no_cache_total"]},
            {"label": "K/V row-projections so far \u2014 cached", "value": state["cached_total"]},
            {"label": "current position being decoded", "value": t},
        ],
        "value_format": "d",
        "caption": "After all three decode steps the no-cache lane will have done 4+5+6=15 K/V projections; the cached lane only ever does 3 \u2014 one per new token.",
    }

    if step == 0:
        text = {
            "kind": "text",
            "text": "Prompt 'the cat sat' has been prefilled (positions 1-3). No decode step has run yet, so neither lane has produced an output vector. Press step to generate the first new token.",
        }
    else:
        text = {
            "kind": "text",
            "text": (
                "Attention output at position " + str(t) + " \u2014 no cache: " + str(state["output_nocache"]) +
                ", cached: " + str(state["output_cached"]) +
                ". The two lanes use exactly the same K and V values, so the numbers match to 3 decimals every step: caching changes how much work is repeated, not what the model computes."
            ),
        }

    panels = [grid, scalars, text]

    if state.get("done"):
        caption = (
            "Across the three generated tokens, no-cache work grows as 4+5+6=15 row-projections "
            "(O(n^2) over a generation of length n), while the cached lane does exactly 3 (O(n)) \u2014 "
            "one new row per step \u2014 and both lanes land on identical attention outputs the whole way."
        )
    else:
        caption = "Step through all three decode positions to see the totals diverge while the outputs stay identical."

    return {"kind": "stack", "panels": panels, "caption": caption}


# ------------------------ what-not-to-cache

def kv_read_counts(prompt_len, gen_len, position):
    prompt_len = int(prompt_len)
    gen_len = int(gen_len)
    position = int(position)
    total_len = prompt_len + gen_len
    if position < 0 or position >= total_len:
        position = 0
    # A query vector is produced at exactly one step (its own) and consumed
    # immediately to compute that step's attention output. It is never read again.
    q_reads = 1
    # A key/value vector, once written, is visible under the causal mask to every
    # subsequent step: the single batched prefill pass, then every decode step.
    k_reads = 1 + gen_len
    return {
        "q_reads": q_reads,
        "k_reads": k_reads,
        "position": position,
        "prompt_len": prompt_len,
        "gen_len": gen_len
    }


def kv_read_heatmap_view(prompt_len, gen_len, highlight_position):
    prompt_len = int(prompt_len)
    gen_len = int(gen_len)
    highlight_position = int(highlight_position)
    if highlight_position < 0 or highlight_position >= prompt_len:
        highlight_position = min(max(highlight_position, 0), max(prompt_len - 1, 0))
    step = max(1, prompt_len // 10)
    positions = list(range(0, prompt_len, step))
    if highlight_position not in positions:
        positions.append(highlight_position)
    positions = sorted(set(positions))
    q_row = [1 for _ in positions]
    k_row = [1 + gen_len for _ in positions]
    col_labels = [str(p) for p in positions]
    highlight_idx = positions.index(highlight_position)
    caption = (
        "Every position's query vector (top row) is read exactly once \u2014 the step that "
        "creates it is the only step that ever needs it. Every position's key vector (bottom "
        "row) is read " + str(1 + gen_len) + " times: once during the batched prefill pass and "
        "once more on each of the " + str(gen_len) + " decode steps, because causal masking "
        "never removes a past position from a later query's window. Position " +
        str(highlight_position) + " is marked; the pattern is the same at every position."
    )
    return {
        "kind": "grid",
        "row_labels": ["Q reads", "K reads"],
        "col_labels": col_labels,
        "cells": [q_row, k_row],
        "x_label": "Sequence position (prompt tokens)",
        "y_label": "Vector",
        "value_format": "d",
        "caption": caption,
        "highlight": [highlight_idx]
    }


# ------------------------ cache-sizing

def dtype_byte_size(dtype):
    sizes = {"fp32": 4, "fp16": 2, "fp8": 1}
    return sizes.get(dtype, 2)


def resolve_kv_preset(preset, n_layers, n_query_heads, n_kv_heads, head_dim):
    presets = {
        "llama3_8b_gqa": (32, 32, 8, 128),
        "mha_variant": (32, 32, 32, 128),
        "mqa_variant": (32, 32, 1, 128),
    }
    if preset in presets:
        return presets[preset]
    return (int(n_layers), int(n_query_heads), int(n_kv_heads), int(head_dim))


def kvcache_model_bytes(n_layers, n_query_heads, head_dim):
    # Rough transformer parameter count: ~4 attention projections + ~8 MLP
    # weights per layer, each roughly d_model^2. Weights are assumed stored
    # in fp16 regardless of the KV cache's own dtype, since in practice the
    # two are quantised independently.
    d_model = n_query_heads * head_dim
    params = 12 * n_layers * d_model * d_model
    return params * 2


def kvcache_cache_bytes(batch, seq_len, n_layers, n_kv_heads, head_dim, dtype):
    return 2 * batch * seq_len * n_layers * n_kv_heads * head_dim * dtype_byte_size(dtype)


def kvcache_max_batch(batch, seq_len, n_layers, n_query_heads, n_kv_heads, head_dim, dtype, preset):
    rl, rq, rkv, rhd = resolve_kv_preset(preset, n_layers, n_query_heads, n_kv_heads, head_dim)
    budget = 80_000_000_000
    weights_bytes = kvcache_model_bytes(rl, rq, rhd)
    available = budget - weights_bytes
    if available <= 0:
        return 0
    per_batch = 2 * seq_len * rl * rkv * rhd * dtype_byte_size(dtype)
    if per_batch <= 0:
        return 0
    return int(available // per_batch)


def kvcache_sizing_view(batch, seq_len, n_layers, n_query_heads, n_kv_heads, head_dim, dtype, preset):
    rl, rq, rkv, rhd = resolve_kv_preset(preset, n_layers, n_query_heads, n_kv_heads, head_dim)
    weights_bytes = kvcache_model_bytes(rl, rq, rhd)
    kv_bytes = kvcache_cache_bytes(batch, seq_len, rl, rkv, rhd, dtype)
    weights_gb = weights_bytes / 1e9
    kv_gb = kv_bytes / 1e9
    hbm_gb = 80.0
    max_batch = kvcache_max_batch(batch, seq_len, n_layers, n_query_heads, n_kv_heads, head_dim, dtype, preset)
    if kv_gb > hbm_gb:
        verdict = "The cache alone (" + format(kv_gb, '.1f') + " GB) is larger than a single H100's 80 GB of HBM: this configuration cannot fit on one GPU."
    elif kv_gb > weights_gb:
        verdict = "The cache (" + format(kv_gb, '.1f') + " GB) already exceeds the model weights (" + format(weights_gb, '.1f') + " GB), even though it fits in 80 GB."
    else:
        verdict = "Here the cache (" + format(kv_gb, '.1f') + " GB) is still smaller than the weights (" + format(weights_gb, '.1f') + " GB)."
    caption = (
        "With " + str(rkv) + " KV head(s), " + str(rl) + " layers, head_dim " + str(rhd) +
        ", batch " + str(batch) + ", context " + str(seq_len) + ", and cache dtype " + str(dtype) +
        ": bytes = 2 * batch * seq * layers * n_kv_heads * head_dim * dtype_bytes. " + verdict +
        " At this context length and architecture, at most " + str(max_batch) +
        " sequences of batch fit in an 80 GB budget after weights."
    )
    bars_panel = {
        "kind": "bars",
        "labels": ["Model weights (fp16)", "KV cache (" + str(dtype) + ")", "H100 HBM (80GB)"],
        "values": [round(weights_gb, 3), round(kv_gb, 3), hbm_gb],
        "y_label": "GB",
        "value_format": ".3f",
        "highlight": [1] if kv_gb > weights_gb else [],
        "caption": caption,
    }
    scalars_panel = {
        "kind": "scalars",
        "items": [
            {"label": "Resolved KV heads", "value": rkv},
            {"label": "Resolved layers", "value": rl},
            {"label": "Bytes per element", "value": dtype_byte_size(dtype)},
            {"label": "KV cache / weights ratio", "value": round(kv_gb / weights_gb, 3) if weights_gb > 0 else 0.0},
            {"label": "Max batch that fits in 80GB", "value": max_batch},
        ],
    }
    return {"kind": "stack", "panels": [bars_panel, scalars_panel], "caption": caption}


def kvcache_size_gb_readout(batch, seq_len, n_layers, n_query_heads, n_kv_heads, head_dim, dtype, preset):
    rl, rq, rkv, rhd = resolve_kv_preset(preset, n_layers, n_query_heads, n_kv_heads, head_dim)
    return round(kvcache_cache_bytes(batch, seq_len, rl, rkv, rhd, dtype) / 1e9, 3)


def kvcache_weights_gb_readout(n_layers, n_query_heads, n_kv_heads, head_dim, preset):
    rl, rq, rkv, rhd = resolve_kv_preset(preset, n_layers, n_query_heads, n_kv_heads, head_dim)
    return round(kvcache_model_bytes(rl, rq, rhd) / 1e9, 3)


def kvcache_max_batch_readout(batch, seq_len, n_layers, n_query_heads, n_kv_heads, head_dim, dtype, preset):
    return kvcache_max_batch(batch, seq_len, n_layers, n_query_heads, n_kv_heads, head_dim, dtype, preset)


# ------------------------ bandwidth-bound

def bandwidth_constants():
    return {
        "model_params": 7e9,
        "bytes_per_param": 2,
        "kv_cache_gb": 2.0,
        "compute_tflops": 312.0,
        "hbm_tbps": 2.0,
        "batch": 1,
        "context": 4096,
    }


def bandwidth_bounds_check():
    c = bandwidth_constants()
    weights_bytes = c["model_params"] * c["bytes_per_param"]
    weights_gb = weights_bytes / 1e9
    kv_bytes = c["kv_cache_gb"] * 1e9
    total_bytes = weights_bytes + kv_bytes
    compute_flops = c["compute_tflops"] * 1e12
    hbm_bytes_per_s = c["hbm_tbps"] * 1e12
    flop_bound_tok_s = compute_flops / (2 * c["model_params"])
    bandwidth_bound_tok_s = hbm_bytes_per_s / total_bytes
    actual_tok_s = min(flop_bound_tok_s, bandwidth_bound_tok_s)
    arithmetic_intensity = (2 * c["model_params"]) / total_bytes
    ridge_point = compute_flops / hbm_bytes_per_s
    return {
        "flop_bound_tok_s": flop_bound_tok_s,
        "bandwidth_bound_tok_s": bandwidth_bound_tok_s,
        "actual_tok_s": actual_tok_s,
        "arithmetic_intensity": arithmetic_intensity,
        "ridge_point": ridge_point,
        "weights_gb": weights_gb,
        "kv_cache_gb": c["kv_cache_gb"],
    }


def bandwidth_batch_scaling(batches=None):
    if not batches:
        batches = [1, 8, 16, 32, 64]
    c = bandwidth_constants()
    weights_bytes = c["model_params"] * c["bytes_per_param"]
    hbm_bytes_per_s = c["hbm_tbps"] * 1e12
    kv_per_seq_bytes = c["kv_cache_gb"] * 1e9
    throughputs = []
    latencies_ms = []
    for b in batches:
        total_bytes = weights_bytes + kv_per_seq_bytes * b
        time_s = total_bytes / hbm_bytes_per_s
        throughputs.append(b / time_s)
        latencies_ms.append(time_s * 1000.0)
    return {"batches": batches, "throughput_tok_s": throughputs, "latency_ms": latencies_ms}


def bandwidth_batch_scaling_view():
    d = bandwidth_batch_scaling()
    thr0 = d["throughput_tok_s"][0]
    thrN = d["throughput_tok_s"][-1]
    lat0 = d["latency_ms"][0]
    latN = d["latency_ms"][-1]
    return {
        "kind": "lines",
        "x": d["batches"],
        "series": [
            {"name": "Aggregate throughput (tok/s)", "values": [round(v, 1) for v in d["throughput_tok_s"]]}
        ],
        "x_label": "Batch size",
        "y_label": "tokens/sec (aggregate)",
        "caption": (
            f"Raising batch size from {d['batches'][0]} to {d['batches'][-1]} lifts aggregate "
            f"throughput from {round(thr0)} to {round(thrN)} tok/s, because the same 14 GB weight "
            f"read is now amortised over many sequences at once. But per-step latency also climbs "
            f"from {lat0:.1f} ms to {latN:.1f} ms, because KV cache bytes read per step scale "
            f"linearly with batch \u2014 eventually cache bytes rival weight bytes and the "
            f"amortisation gains taper off."
        ),
    }


def bandwidth_reveal_view():
    r = bandwidth_bounds_check()
    gap = r["flop_bound_tok_s"] / r["bandwidth_bound_tok_s"]
    ridge_gap = r["ridge_point"] / r["arithmetic_intensity"]
    bars_panel = {
        "kind": "bars",
        "labels": ["If compute-bound", "Actual (bandwidth-bound)"],
        "values": [round(r["flop_bound_tok_s"], 1), round(r["bandwidth_bound_tok_s"], 1)],
        "y_label": "tokens/sec",
        "caption": (
            f"A FLOP-counting model predicts ~{round(r['flop_bound_tok_s']):,} tok/s, but each decode "
            f"step actually streams {r['weights_gb']:.0f} GB of weights plus {r['kv_cache_gb']:.0f} GB "
            f"of KV cache from HBM, capping real throughput at ~{round(r['bandwidth_bound_tok_s'])} "
            f"tok/s \u2014 about {round(gap)}x lower than the compute-only estimate."
        ),
    }
    scalars_panel = {
        "kind": "scalars",
        "items": [
            {"label": "Arithmetic intensity (FLOP/byte)", "value": round(r["arithmetic_intensity"], 2)},
            {"label": "A100 ridge point (FLOP/byte)", "value": round(r["ridge_point"], 1)},
        ],
        "caption": (
            f"Arithmetic intensity of roughly {r['arithmetic_intensity']:.1f} FLOP/byte sits about "
            f"{round(ridge_gap)}x below the hardware's ridge point of {r['ridge_point']:.0f} \u2014 "
            f"decode never gets close to using the GPU's compute throughput; it's entirely limited "
            f"by how fast bytes can be pulled from memory."
        ),
    }
    batch_panel = bandwidth_batch_scaling_view()
    return {"kind": "stack", "panels": [bars_panel, scalars_panel, batch_panel]}
